CREATE DATABASE customer_behavior;
USE customer_behavior;

-- 1. what is the total revenue generated by male vs female

select * from customer limit 10;

SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
group by gender;

-- 2. which customers used discount but still spent more than avg purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (SELECT avg(purchase_amount) from customer);

--  which are the top 5 products with the highest average review rating 
select item_purchased, round(avg(review_rating),2) as "Avg Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. compare the avg purchase amounts between standard and express shipping

select shipping_type,
avg(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5. Do subscribed customer spend more compare average spend with total revenue between subscriber and non subscriber
SELECT subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
SUM(purchase_amount) AS total_revenue 
FROM customer
group by subscription_status;

-- which 5 products have the highest percentage of purchases with discount applied 

select item_purchased,
sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100 as discount_rates
from customer
group by item_purchased
order by discount_rates desc
limit 5;

-- 7. segement customer into new , returning and loyal based on their total number of previous purchases, and show the count of each segement

with customer_type as(
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customer"
from customer_type
group by customer_segment;

-- what are the top three most purchased products in each category 

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- are customers who are repat buyers more than 5 previous purchases also likely to subscribe

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group 
select age_group, SUM(purchase_amount) AS revenue 
FROM customer
group by age_group;



